# Generated by Django 4.2.14 on 2024-07-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='universityranking',
            table='university_rankings',
        ),
    ]
